only_rules:
- array_init
- attributes
- class_delegate_protocol
- closing_brace
- closure_body_length
- closure_end_indentation
- closure_parameter_position
- closure_spacing
- collection_alignment
- colon
- comma
- comma_inheritance
- compiler_protocol_init
- computed_accessors_order
- contains_over_filter_count
- contains_over_filter_is_empty
- contains_over_first_not_nil
- contains_over_range_nil_comparison
- control_statement
- convenience_type
- cyclomatic_complexity
- deployment_target
- direct_return
- discouraged_direct_init
- duplicate_conditions
- duplicate_enum_cases
- duplicate_imports
- duplicated_key_in_dictionary_literal
- empty_collection_literal
- empty_count
- empty_enum_arguments
- empty_parameters
- empty_parentheses_with_trailing_closure
- empty_string
- empty_xctest_method
- enum_case_associated_values_count
- explicit_init
- explicit_self
- extension_access_modifier
- fallthrough
- fatal_error_message
- file_length
- file_name
- file_name_no_space
- file_types_order
- first_where
- flatmap_over_map_reduce
- for_where
- force_cast
- force_try
- force_unwrapping
- function_body_length
- function_default_parameter_at_end
- function_parameter_count
- generic_type_name
- ibinspectable_in_extension
- identical_operands
- identifier_name
- implicit_getter
- implicit_return
- is_disjoint
- joined_default_parameter
- large_tuple
- last_where
- leading_whitespace
- legacy_cggeometry_functions
- legacy_constant
- legacy_constructor
- legacy_hashing
- legacy_multiple
- legacy_nsgeometry_functions
- legacy_objc_type
- legacy_random
- let_var_whitespace
- line_length
- literal_expression_end_indentation
- lower_acl_than_parent
- mark
- modifier_order
- multiline_arguments
- multiline_function_chains
- multiline_literal_brackets
- multiline_parameters
- multiple_closures_with_trailing_closure
- nesting
- no_space_in_method_call
- non_overridable_class_declaration
- ns_number_init_as_function_reference
- nsobject_prefer_isequal
- number_separator
- opening_brace
- operator_usage_whitespace
- operator_whitespace
- optional_enum_case_matching
- orphaned_doc_comment
- overridden_super_call
- prefer_self_in_static_references
- prefer_self_type_over_type_of_self
- prefer_zero_over_explicit_init
- prefixed_toplevel_constant
- private_action
- private_outlet
- private_over_fileprivate
- private_subject
- protocol_property_accessors_order
- reduce_boolean
- reduce_into
- redundant_discardable_let
- redundant_nil_coalescing
- redundant_objc_attribute
- redundant_optional_initialization
- redundant_set_access_control
- redundant_string_enum_value
- redundant_type_annotation
- redundant_void_return
- return_arrow_whitespace
- return_value_from_void_function
- self_binding
- self_in_property_initialization
- shorthand_operator
- shorthand_optional_binding
- sorted_first_last
- statement_position
- static_operator
- superfluous_else
- switch_case_alignment
- syntactic_sugar
- todo
- toggle_bool
- trailing_closure
- trailing_comma
- trailing_newline
- trailing_semicolon
- type_contents_order
- type_name
- typesafe_array_init
- unavailable_function
- unhandled_throwing_task
- unneeded_break_in_switch
- unneeded_override
- unneeded_parentheses_in_closure_argument
- unneeded_synthesized_initializer
- unowned_variable_capture
- untyped_error_in_catch
- unused_closure_parameter
- unused_control_flow_label
- unused_declaration
- unused_enumerated
- unused_import
- unused_setter_value
- valid_ibinspectable
- vertical_whitespace
- vertical_whitespace_between_cases
- vertical_whitespace_closing_braces
- void_function_in_ternary
- void_return
- weak_delegate
- xctfail_message
- yoda_condition
- local_doc_comment

excluded:
- Package.swift
- ToolsboxSDK.swift

array_init:
    severity: warning

attributes:
    severity: warning

class_delegate_protocol:
    severity: error

closing_brace:
    severity: warning

closure_body_length:
    warning: 35

closure_end_indentation:
    severity: warning

closure_parameter_position:
    severity: warning

closure_spacing:
    severity: warning

collection_alignment:
    severity: warning

colon:
    severity: warning

comma:
    severity: warning
    
comma_inheritance:
    severity: warning

compiler_protocol_init:
    severity: warning
    
computed_accessors_order:
    severity: warning

contains_over_filter_count:
    severity: error

contains_over_filter_is_empty:
    severity: error

contains_over_first_not_nil:
    severity: error

contains_over_range_nil_comparison:
    severity: error

control_statement:
    severity: warning
    
convenience_type:
    severity: error

cyclomatic_complexity:
    warning: 10
    ignores_case_statements: true
    
direct_return:
    severity: error

deployment_target:
    severity: error

discouraged_direct_init:
    severity: error

duplicate_conditions:
    severity: error
    
duplicate_enum_cases:
    severity: error
    
duplicate_imports:
    severity: error
    
duplicated_key_in_dictionary_literal:
    severity: warning

empty_collection_literal:
    severity: warning

empty_count:
    severity: warning

empty_enum_arguments:
    severity: warning

empty_parameters:
    severity: warning

empty_parentheses_with_trailing_closure:
    severity: warning

empty_string:
    severity: warning

empty_xctest_method:
    severity: warning

enum_case_associated_values_count:
    warning: 5
    
explicit_init:
    severity: error

explicit_self:
    severity: error
    
extension_access_modifier:
    severity: warning

fallthrough:
    severity: error

fatal_error_message:
    severity: error

file_length:
    warning: 500
    ignore_comment_only_lines: true
    
file_name:
    severity: warning

file_name_no_space:
    severity: error

file_types_order:
    severity: warning

first_where:
    severity: error

flatmap_over_map_reduce:
    severity: error

for_where:
    severity: warning

force_cast:
    severity: error

force_try:
    severity: error

force_unwrapping:
    severity: error

function_body_length:
    warning: 80

function_default_parameter_at_end:
    severity: warning
    
function_parameter_count:
    warning: 5

generic_type_name:
    severity: warning
    
ibinspectable_in_extension:
    severity: warning

identical_operands:
    severity: error

identifier_name:
    min_length:
        warning: 2
    max_length:
        warning: 35
    allowed_symbols:
        - "_"
    excluded:
        - id
        - i
        - x
        - y
        - z

implicit_getter:
    severity: warning

implicit_return:
    severity: warning

is_disjoint:
    severity: error

joined_default_parameter:
    severity: error

large_tuple:
    warning: 3

last_where:
    severity: error
    
leading_whitespace:
    severity: warning

legacy_cggeometry_functions:
    severity: error

legacy_constant:
    severity: error

legacy_constructor:
    severity: error

legacy_hashing:
    severity: error

legacy_multiple:
    severity: error

legacy_nsgeometry_functions:
    severity: error
    
legacy_objc_type:
    severity: error

legacy_random:
    severity: error
    
let_var_whitespace:
    severity: warning

line_length:
    warning: 130
    ignores_urls: true
    ignores_function_declarations: false
    ignores_comments: true
    ignores_interpolated_strings: true

literal_expression_end_indentation:
    severity: warning

lower_acl_than_parent:
    severity: error

mark:
    severity: warning
    
modifier_order:
    severity: warning

multiline_arguments:
    severity: warning

multiline_function_chains:
    severity: warning

multiline_literal_brackets:
    severity: warning

multiline_parameters:
    severity: warning

multiple_closures_with_trailing_closure:
    severity: warning

nesting:
    type_level:
        warning: 3
    function_level:
        warning: 3

no_space_in_method_call:
    severity: warning
    
ns_number_init_as_function_reference:
    severity: warning
    
non_overridable_class_declaration:
    severity: warning

nsobject_prefer_isequal:
    severity: error

number_separator:
    severity: warning
    minimum_length: 5

opening_brace:
    severity: warning

operator_usage_whitespace:
    severity: warning

operator_whitespace:
    severity: warning

optional_enum_case_matching:
    severity: warning

orphaned_doc_comment:
    severity: warning

overridden_super_call:
    severity: error
    
prefer_self_in_static_references:
    severity: warning

prefer_self_type_over_type_of_self:
    severity: warning
    
prefer_zero_over_explicit_init:
    severity: warning

prefixed_toplevel_constant:
    severity: warning

private_action:
    severity: warning

private_outlet:
    severity: warning

private_over_fileprivate:
    severity: warning
    
private_subject:
    severity: warning

protocol_property_accessors_order:
    severity: warning

reduce_boolean:
    severity: error

reduce_into:
    severity: error

redundant_discardable_let:
    severity: warning

redundant_nil_coalescing:
    severity: warning

redundant_objc_attribute:
    severity: warning

redundant_optional_initialization:
    severity: warning

redundant_set_access_control:
    severity: warning

redundant_string_enum_value:
    severity: error

redundant_type_annotation:
    severity: warning

redundant_void_return:
    severity: warning

return_arrow_whitespace:
    severity: warning
    
return_value_from_void_function:
    severity: warning
    
self_binding:
    severity: warning

self_in_property_initialization:
    severity: error

shorthand_operator:
    severity: warning
    
shorthand_optional_binding:
    severity: warning

sorted_first_last:
    severity: error

statement_position:
    severity: warning

static_operator:
    severity: warning
    
superfluous_else:
    severity: warning

switch_case_alignment:
    severity: warning

syntactic_sugar:
    severity: warning

todo:
    severity: warning

toggle_bool:
    severity: warning

trailing_closure:
    severity: warning

trailing_comma:
    severity: warning

trailing_newline:
    severity: warning

trailing_semicolon:
    severity: warning

type_contents_order:
    severity: warning
    order:
        - case
        - type_alias
        - associated_type
        - subtype
        - ib_outlet
        - ib_inspectable
        - type_property
        - type_method
        - instance_property
        - initializer
        - deinitializer
        - view_life_cycle_method
        - other_method
        - ib_action
        - subscript

type_name:
    min_length:
        warning: 2
    max_length:
        warning: 35
        
typesafe_array_init:
    severity: warning

unavailable_function:
    severity: error
    
unhandled_throwing_task:
    severity: warning

unneeded_break_in_switch:
    severity: warning
    
unneeded_override:
    severity: warning

unneeded_parentheses_in_closure_argument:
    severity: warning
    
unneeded_synthesized_initializer:
    severity: warning

unowned_variable_capture:
    severity: warning
    
untyped_error_in_catch:
    severity: warning
    
unused_closure_parameter:
    severity: warning

unused_control_flow_label:
    severity: warning

unused_declaration:
    severity: warning

unused_enumerated:
    severity: warning

unused_import:
    severity: warning

unused_setter_value:
    severity: warning

valid_ibinspectable:
    severity: warning

vertical_whitespace:
    severity: warning
    
vertical_whitespace_between_cases:
   severity: warning

vertical_whitespace_closing_braces:
   severity: warning
   
void_function_in_ternary:
   severity: warning

void_return:
    severity: warning

weak_delegate:
    severity: error

xctfail_message:
    severity: warning

yoda_condition:
    severity: warning
    
local_doc_comment:
    severity: error

reporter: "xcode"
