name: PR Validation

on:
  pull_request_target:
    types: [opened, synchronize]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    if: github.event.pull_request.state == 'open'
    
    runs-on: macos-14

    strategy:
      matrix:
        scheme:
          [
            "ToolsboxSDK-Package",
            "ToolsboxSDK_Core",
            "ToolsboxSDK_UI",
            "ToolsboxSDK_Helpers",
            "ToolsboxSDK_Network",
          ]

    steps:
      - name: "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
        run: echo "OK"

      - name: "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
        run: echo "OK"

      - name: Checkout ToolsboxSDK
        uses: actions/checkout@v4

      - name: Install SwiftLint
        run: brew install swiftlint

      - name: Install xcbeautify
        run: brew install xcbeautify

      - name: Run SwiftLint
        run: swiftlint lint --strict --reporter github-actions-logging

      - name: Select Xcode version
        run: sudo xcode-select -switch /Applications/Xcode_15.3.app

      - name: Build ToolsboxSDK with scheme "${{ matrix.scheme }}"
        run: set -o pipefail && xcodebuild -scheme "${{ matrix.scheme }}" -destination "generic/platform=iOS" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO -skipPackagePluginValidation -skipMacroValidation clean build | xcbeautify
