name: PR Validation

on:
  pull_request:
    branches:
      - develop

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build:

    runs-on: macos-14

    steps:
        - name: Checkout ToolsboxSDK repo
          uses: actions/checkout@v4
          
        - name: Install SwiftLint
          run: brew install swiftlint
          
        - name: Install xcbeautify
          run: brew install xcbeautify
        
        - name: Run SwiftLint
          run: swiftlint lint --reporter github-actions-logging

        - name: Select Xcode version
          run: sudo xcode-select -switch /Applications/Xcode_15.3.app

        - name: Build ToolsboxSDK
          run: set -o pipefail && xcodebuild -scheme ToolsboxSDK-Package -destination "generic/platform=iOS" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO clean build | xcbeautify
